name: transcendence

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      NODE_ENV: production
      PORT: 3000
      SQLITE_PATH: /database/database.sqlite
    expose:
      - "3000"
    volumes:
      - backend_data:/data
    restart: unless-stopped
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:

volumes:
  pg_data:
  backend_data:   # uncomment if you use SQLite inside backend