user www-data www-data;

worker_processes 2;

error_log /var/log/nginx/error_log info;

load_module /usr/lib/nginx/modules/ngx_http_modsecurity_module.so;

events {
    worker_connections 1024;
}

http {
  server {
    listen 80;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl http2;
    server_name _;

    ssl_certificate     /etc/ssl/local/fullchain.pem;
    ssl_certificate_key /etc/ssl/local/privkey.pem;

    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsec/main.conf;

    # Frontend (Vite dev server)
    location / {
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://frontend:5173;
    }

    # Backend API
    location /api/ {
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://backend:3000;
    }

    # WebSocket (if your backend exposes it at /ws)
    location /wss {
	  proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_http_version 1.1;
      proxy_read_timeout 3600s;
      proxy_pass http://backend:3000/wss;
    }
  }

}

