
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('tester1');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('password');
  await page.locator('form').getByRole('button', { name: 'Register' }).click();
  await expect(page.getByRole('link', { name: 'Exit' })).toBeVisible();
  await page.getByRole('link', { name: 'Exit' }).click();
  await page.getByRole('button', { name: 'Exit' }).click();
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('tester2');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('password');
  await page.locator('form').getByRole('button', { name: 'Register' }).click();
  await expect(page.getByRole('link', { name: 'Exit' })).toBeVisible();
  await page.getByRole('link', { name: 'Exit' }).click();
  await page.getByRole('button', { name: 'Exit' }).click();
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('tester3');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('password');
  await page.locator('form').getByRole('button', { name: 'Register' }).click();
  await expect(page.getByRole('link', { name: 'Exit' })).toBeVisible();
  await page.getByRole('link', { name: 'Exit' }).click();
  await page.getByRole('button', { name: 'Exit' }).click();
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('tester4');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('password');
  await page.locator('form').getByRole('button', { name: 'Register' }).click();
  await expect(page.getByRole('link', { name: 'Exit' })).toBeVisible();
  await page.getByRole('link', { name: 'Exit' }).click();
  await page.getByRole('button', { name: 'Exit' }).click();
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('tester5');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('password');
  await page.locator('form').getByRole('button', { name: 'Register' }).click();
  await page.getByRole('link', { name: 'Tournament' }).click();
  await page.getByRole('button', { name: 'Start a new tournament' }).click();
  await page.getByRole('textbox', { name: 'Alias' }).first().click();
  await page.getByRole('textbox', { name: 'Alias' }).first().fill('teddy5');
  await page.getByRole('button', { name: 'Set Alias' }).click();
  await page.getByRole('textbox', { name: 'Username' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Username' }).nth(1).fill('tester4');
  await page.getByRole('textbox', { name: 'Password' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Password' }).nth(1).fill('password');
  await page.getByRole('textbox', { name: 'Alias' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Alias' }).nth(1).fill('teddy4');
  await page.getByRole('button', { name: 'Add Player' }).first().click();
  await page.getByRole('textbox', { name: 'Username' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Username' }).nth(2).fill('tester3');
  await page.getByRole('textbox', { name: 'Password' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Password' }).nth(2).fill('password');
  await page.getByRole('textbox', { name: 'Alias' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Alias' }).nth(2).fill('teddy3');
  await page.getByRole('button', { name: 'Add Player' }).first().click();
  await page.getByRole('textbox', { name: 'Username' }).nth(3).click();
  await page.getByRole('textbox', { name: 'Username' }).nth(3).fill('tester2');
  await page.getByRole('textbox', { name: 'Password' }).nth(3).click();
  await page.getByRole('textbox', { name: 'Password' }).nth(3).fill('password');
  await page.getByRole('textbox', { name: 'Alias' }).nth(3).click();
  await page.getByRole('textbox', { name: 'Alias' }).nth(3).fill('teddy2');
  await page.getByRole('button', { name: 'Add Player' }).click();
  await page.getByRole('button', { name: 'Start Tournament' }).click();
  await expect(page.getByRole('link', { name: 'Exit' })).toBeVisible();
  await page.getByRole('link', { name: 'Exit' }).click();
  await page.getByRole('button', { name: 'Exit' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('tester2');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('password');
  await page.locator('form').getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByRole('button', { name: 'Delete profile' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('tester5');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('password');
  await page.locator('form').getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Tournament' }).click();
  await page.getByRole('textbox', { name: 'Username' }).nth(3).click();
  await page.getByRole('textbox', { name: 'Username' }).nth(3).fill('tester1');
  await page.getByRole('textbox', { name: 'Password' }).nth(3).click();
  await page.getByRole('textbox', { name: 'Password' }).nth(3).fill('password');
  await page.getByRole('textbox', { name: 'Alias' }).nth(3).click();
  await page.getByRole('textbox', { name: 'Alias' }).nth(3).fill('teddy1');
  await page.getByRole('button', { name: 'Add Player' }).click();
  await page.getByRole('button', { name: 'Start Tournament' }).click();
  await page.getByRole('button', { name: 'Play Match 1' }).click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('');
  await page.getByRole('spinbutton').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Start game' }).click();
  await page.locator('iframe').contentFrame().getByText('OK').click();
  await page.getByRole('button', { name: 'Play Match 2' }).click();
  await page.locator('iframe').contentFrame().getByText('OK').click();
  await expect(page.getByRole('link', { name: 'Exit' })).toBeVisible();
  await page.getByRole('link', { name: 'Exit' }).click();
  await page.getByRole('button', { name: 'Exit' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('tester3');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('password');
  await page.locator('form').getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByRole('button', { name: 'Delete profile' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('tester6');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('password');
  await page.locator('form').getByRole('button', { name: 'Register' }).click();
  await expect(page.getByRole('link', { name: 'Exit' })).toBeVisible();
  await page.getByRole('link', { name: 'Exit' }).click();
  await page.getByRole('button', { name: 'Exit' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('tester5');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('password');
  await page.locator('form').getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Tournament' }).click();
  await page.getByRole('textbox', { name: 'Username' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Username' }).nth(2).fill('tester6');
  await page.getByRole('textbox', { name: 'Password' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Password' }).nth(2).fill('password');
  await page.getByRole('textbox', { name: 'Alias' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Alias' }).nth(2).fill('teddy6');
  await page.getByRole('button', { name: 'Add Player' }).click();
  await page.getByRole('button', { name: 'Start Tournament' }).click();
  await page.getByRole('button', { name: 'Play Match 2' }).click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('');
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Start game' }).click();
  await page.locator('iframe').contentFrame().getByText('OK').click();
  await page.getByRole('button', { name: 'Play Final' }).click();
  await page.locator('div').filter({ hasText: 'TournamentWinner🏆' }).nth(3).click();
});
