name: Fullstack CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  fullstack-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install backend dependencies
        run: npm install --prefix backend

      - name: install frontend dependencies
        run: npm install --prefix frontend

      - name: Install concurrently
        run: npm install --save-dev concurrently wait-on

      - name: Run fullstack
        run: |
          npx concurrently \
            "npm start --prefix backend" \
            "npm run dev --prefix frontend" \
            "npx wait-on http://localhost:3000"

      - name: run tests
        run: npm test
